
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: hello_db
  host: localhost
  pool: 5
  username: postgres
  password: Abby2020#
  port: 5432

test:
  <<: *default
  database: hello_test
  username: postgres
  password: Abby2020#

production:
  <<: *default
  database: hello_production
  username: hello
  password: <%= ENV["HELLO_DATABASE_PASSWORD"] %>






# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: Rails_Blog_development
#   encoding: unicode
#   pool: 5

#   username: postgres
#   password: 12

# test:
#   <<: *default
#   database: Rails_Blog_test
#   encoding: unicode
#   pool: 5
#   username: postgres
#   password: 12

# production:
#   <<: *default
#   database: Rails_Blog_production
#   username: Rails_Blog
#   password: <%= ENV["RAILS_BLOG_DATABASE_PASSWORD"] %>
